name: Testing

on:
  push:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2', '8.3']
    env:
      extensions: bcmath
    steps:
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.extensions }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Install Dependencies
        run: composer install --prefer-dist
      - name: Check code style
        run: composer sniff
      - name: Testing
        run: composer test
